version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - grafana-net
    volumes:
      - grafana-volume
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - grafana-net


  myservice:
    build: .
    depends_on: ["db"]
    container_name: "SpringDemo"
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/demotask

  db:
    image: "postgres"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demotask
      - POSTGRES_HOST_AUTH_METHOD= trust
    volumes:
      - ./src/main/resources/sql:/docker-entrypoint-initdb.d/
      - ./postgres-data:/var/lib/postgresql/data


networks:
  grafana-net: